[view][feature] 実機で動作させてcanvasサイズを調整する
mznh/digital-catan pull request #37
Opened 2021-04-27 13:05 UTC by jityoudou

#22 へのPRです

元々の 一度再生したら消滅 の挙動に加えて以下の2つを追加します。
機能 挙動 理由
    一度再生したら停止
    ループ再生

DrawableAnimationObject 生成時に ANIMATION_TYPE を指定することでこれらを切り替えます。

各タイプによる挙動の違いは AnimationStatus 内の isFinished, nextFrame で表現しています。

2021-04-27 13:23 UTC, mznh requested changes
これ` main-canvas/main-canvas.component.html` を編集していないので、デバック用のボタンが表示されたまま = このまま全画面にしても画面表示が液晶と合わない と思うのだけど・・・

2021-04-27 13:23 UTC, mznh commented on tile-view/package.json
> +    "start": "ng serve --open",
ここ、自動起動のために追加したのだと思うのだけど、 `start` は `start_service` 等で呼ばれることがあるので、別のコマンドを追加する形のほうが良いと思います。

例えば ` "autorun": "ng serve --open"`

2021-04-27 13:23 UTC, mznh commented on tile-view/src/app/service/view-command/view-command.service.ts
> +    this.p5ref.push();
枠線を描画するところは別の関数、例えば `drawScreenEdge` とかにまとめたほうが良いかと思います。

2021-04-27 15:48 UTC, mznh commented
現行のデバックボタンつきのhtmlは `localhost:4200/debug` で提供するとかにしたら良さそう

2021-04-30 16:54 UTC, mznh commented on tile-view/exec
> +npm run autorun
今回のPRでは自動起動を扱わないはずなので、exec は書き換えないでください

2021-04-30 16:55 UTC, jityoudou commented
レビューありがとうございます。
ボタンの削除、ディスプレイの淵描画の関数化を反映させます。

2021-04-30 16:57 UTC, mznh approved these changes
LGTM

2021-04-30 16:57 UTC, merged